version: '3.8'

services:
  app:
    image: melihemreguler/donusturkiye-backend:latest
    container_name: golang_app
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "8080:8080"
    networks:
      - backend
    command: ./main

networks:
  backend: